# image_gen.py
from PIL import Image, ImageDraw, ImageFont
import os
import math

def generate_summary_image(cache_dir, total_countries, top_countries, last_refreshed_at):
    """
    top_countries: list of dicts: [{'name':..., 'estimated_gdp':...}, ...]
    last_refreshed_at: ISO string
    """
    os.makedirs(cache_dir, exist_ok=True)
    path = os.path.join(cache_dir, "summary.png")

    width, height = 1200, 800
    img = Image.new("RGBA", (width, height), (255, 255, 255, 255))
    draw = ImageDraw.Draw(img)

    # Try to load a basic font; fallback to default
    try:
        font_title = ImageFont.truetype("DejaVuSans-Bold.ttf", 40)
        font_text = ImageFont.truetype("DejaVuSans.ttf", 20)
    except Exception:
        font_title = ImageFont.load_default()
        font_text = ImageFont.load_default()

    # Title
    draw.text((40, 30), "Countries Summary", font=font_title, fill=(0,0,0))
    draw.text((40, 90), f"Total countries cached: {total_countries}", font=font_text, fill=(0,0,0))
    draw.text((40, 120), f"Last refreshed at (UTC): {last_refreshed_at}", font=font_text, fill=(0,0,0))

    draw.text((40, 170), "Top 5 countries by estimated GDP (USD-equivalent):", font=font_text, fill=(0,0,0))

    y = 210
    for i, c in enumerate(top_countries[:5], start=1):
        name = c.get("name", "N/A")
        gdp = c.get("estimated_gdp")
        if gdp is None:
            gdp_text = "N/A"
        else:
            # human readable
            if gdp >= 1_000_000_000:
                gdp_text = f"${gdp/1_000_000_000:,.2f}B"
            elif gdp >= 1_000_000:
                gdp_text = f"${gdp/1_000_000:,.2f}M"
            else:
                gdp_text = f"${gdp:,.2f}"

        draw.text((60, y), f"{i}. {name}: {gdp_text}", font=font_text, fill=(0,0,0))
        y += 40

    # small footer
    draw.text((40, height - 40), "Generated by Country Currency & Exchange API", font=font_text, fill=(100,100,100))

    img.save(path)
    return path
